@startuml

title __APP's Class Diagram__\n

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.BookAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.ForumAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.LibraryAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.MessageAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.MyBooksAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.ReviewAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.SwipeToDeleteCallback {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Adapters {
      class com.example.qainfomate.Adapters.TopicAdapter {
      }
    }
  }
  

  namespace com.example.qainfomate {
    class com.example.qainfomate.BuildConfig {
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      abstract class com.example.qainfomate.Models.Book {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Book_for_Sale {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      interface com.example.qainfomate.Models.GenericList {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Library_Book {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Message {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Review {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Session {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Thread {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.Topic {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace Models {
      class com.example.qainfomate.Models.User {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.AddForumComment {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Book_for_sale_detail {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Dashboard {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Floors {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.ItemListClass {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Library {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.LibraryBookDetail {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.MainActivity {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.MessageDetail {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.MyBookDetail {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.NewTopic {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Post_Book {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Post_Book2 {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Post_lib_Book {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Post_lib_Book2 {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Post_review {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Register {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.SendMsg {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Splash {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Support {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Support2 {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.Timetable {
      }
    }
  }
  

  namespace com.example.qainfomate {
    namespace View {
      class com.example.qainfomate.View.TopicDetail {
      }
    }
  }
  

  com.example.qainfomate.Adapters.BookAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Adapters.BookAdapter o-- com.example.qainfomate.Adapters.BookAdapter.Holder.recInterface : listener
  com.example.qainfomate.Adapters.ForumAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Adapters.ForumAdapter o-- com.example.qainfomate.Adapters.ForumAdapter.Holder.ForumInterface : listener
  com.example.qainfomate.Adapters.LibraryAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Adapters.LibraryAdapter o-- com.example.qainfomate.Adapters.LibraryAdapter.Holder.recInterface : listener
  com.example.qainfomate.Adapters.MessageAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Adapters.MessageAdapter o-- com.example.qainfomate.Adapters.MessageAdapter.Holder.MsgInterface : listener
  com.example.qainfomate.Adapters.MessageAdapter o-- com.example.qainfomate.Models.Message : mRecentlyDeletedItem
  com.example.qainfomate.Adapters.MyBooksAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Adapters.MyBooksAdapter o-- com.example.qainfomate.Adapters.MyBooksAdapter.Holder.recInterface : listener
  com.example.qainfomate.Adapters.ReviewAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Adapters.ReviewAdapter o-- com.example.qainfomate.Adapters.ReviewAdapter.Holder.recInterface : listener
  com.example.qainfomate.Adapters.SwipeToDeleteCallback -up-|> androidx.recyclerview.widget.ItemTouchHelper.SimpleCallback
  com.example.qainfomate.Adapters.SwipeToDeleteCallback o-- com.example.qainfomate.Adapters.MessageAdapter : mAdapter
  com.example.qainfomate.Adapters.TopicAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.qainfomate.Models.Book .up.|> android.os.Parcelable
  com.example.qainfomate.Models.Book_for_Sale .up.|> android.os.Parcelable
  com.example.qainfomate.Models.Book_for_Sale .up.|> com.example.qainfomate.Models.GenericList
  com.example.qainfomate.Models.Book_for_Sale -up-|> com.example.qainfomate.Models.Book
  com.example.qainfomate.Models.Library_Book .up.|> android.os.Parcelable
  com.example.qainfomate.Models.Library_Book -up-|> com.example.qainfomate.Models.Book
  com.example.qainfomate.Models.Message .up.|> android.os.Parcelable
  com.example.qainfomate.Models.Message .up.|> com.example.qainfomate.Models.GenericList
  com.example.qainfomate.Models.Topic .up.|> android.os.Parcelable
  com.example.qainfomate.Models.Topic .up.|> com.example.qainfomate.Models.GenericList
  com.example.qainfomate.View.AddForumComment -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.AddForumComment o-- com.example.qainfomate.Models.Thread : thread
  com.example.qainfomate.View.AddForumComment o-- com.example.qainfomate.Models.Topic : topic
  com.example.qainfomate.View.Book_for_sale_detail -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Dashboard -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Floors -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.ItemListClass .up.|> com.example.qainfomate.Adapters.BookAdapter.Holder.recInterface
  com.example.qainfomate.View.ItemListClass .up.|> com.example.qainfomate.Adapters.ForumAdapter.Holder.ForumInterface
  com.example.qainfomate.View.ItemListClass .up.|> com.example.qainfomate.Adapters.MessageAdapter.Holder.MsgInterface
  com.example.qainfomate.View.ItemListClass .up.|> com.example.qainfomate.Adapters.MyBooksAdapter.Holder.recInterface
  com.example.qainfomate.View.ItemListClass -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.ItemListClass o-- com.example.qainfomate.Adapters.BookAdapter : bookAdapter
  com.example.qainfomate.View.ItemListClass o-- com.example.qainfomate.Adapters.ForumAdapter : forumAdapter
  com.example.qainfomate.View.ItemListClass o-- com.example.qainfomate.Adapters.MessageAdapter : msgAdapter
  com.example.qainfomate.View.ItemListClass o-- com.example.qainfomate.Adapters.MyBooksAdapter : myBooksAdapter
  com.example.qainfomate.View.Library .up.|> com.example.qainfomate.Adapters.LibraryAdapter.Holder.recInterface
  com.example.qainfomate.View.Library -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Library o-- com.example.qainfomate.Adapters.LibraryAdapter : libAdapter
  com.example.qainfomate.View.LibraryBookDetail .up.|> com.example.qainfomate.Adapters.ReviewAdapter.Holder.recInterface
  com.example.qainfomate.View.LibraryBookDetail -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.LibraryBookDetail o-- com.example.qainfomate.Adapters.ReviewAdapter : adapter
  com.example.qainfomate.View.LibraryBookDetail o-- com.example.qainfomate.Models.Library_Book : libbook
  com.example.qainfomate.View.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.MessageDetail -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.MyBookDetail -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.NewTopic -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.NewTopic o-- com.example.qainfomate.Models.Topic : topic
  com.example.qainfomate.View.Post_Book -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Post_Book2 -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Post_lib_Book -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Post_lib_Book2 -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Post_review -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Post_review o-- com.example.qainfomate.Models.Library_Book : lb
  com.example.qainfomate.View.Post_review o-- com.example.qainfomate.Models.Review : rv
  com.example.qainfomate.View.Register -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.SendMsg -up-|> android.app.Activity
  com.example.qainfomate.View.Splash -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Support -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Support2 -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.Timetable -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.TopicDetail -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.qainfomate.View.TopicDetail o-- com.example.qainfomate.Adapters.TopicAdapter : adapter
  com.example.qainfomate.View.TopicDetail o-- com.example.qainfomate.Models.Thread : thread
  com.example.qainfomate.View.TopicDetail o-- com.example.qainfomate.Models.Topic : topic


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
